#!/usr/bin/env python3
"""Inline local Phosphor symbols for consistent rendering without external SVG use."""
from pathlib import Path
import re, sys
root=Path(__file__).resolve().parents[1]
sprite=(root/'assets/phosphor/icons.svg').read_text()
symbols=dict(re.findall(r'<symbol id="([^"]+)"[^>]*>(.*?)</symbol>',sprite,re.S))
check='--check' in sys.argv
changed=[]
for file in [*root.glob('*.html'),*(root/'pages').glob('*.html')]:
 source=file.read_text()
 def inline(match):
  attrs,body=match.groups()
  key=re.search(r'data-phosphor="([^"]+)"',attrs)
  use=re.search(r'<use href="(?:\.\./)?assets/phosphor/icons.svg#([^"]+)"',body)
  if not key and not use:return match.group()
  name=(key or use).group(1)
  if name not in symbols:raise SystemExit('Unknown Phosphor icon: '+name)
  if not key:attrs+=' data-phosphor="'+name+'"'
  return '<svg'+attrs+'>'+symbols[name]+'</svg>'
 result=re.sub(r'<svg([^>]*)>(.*?)</svg>',inline,source,flags=re.S)
 if result!=source:
  changed.append(str(file.relative_to(root)))
  if not check:file.write_text(result)
# Review menu consumes the same generated source, never external SVG references.
import json
path=root/'js/phosphor.js'
result='/* Generated by tools/sync_icons.py from official local SVGs. */\nwindow.PHOSPHOR = '+json.dumps(symbols,separators=(',',':'))+';\n'
if not path.exists() or path.read_text()!=result:
 changed.append('js/phosphor.js')
 if not check:path.write_text(result)
if check and changed:raise SystemExit('Run python3 tools/sync_icons.py: '+', '.join(changed))
print('PASS: Phosphor inline assets synchronized' if check else 'Synchronized Phosphor inline assets')
